name: Static Analysis
on: [push]
jobs:
  Run-Eslint:
    runs-on: ubuntu-latest
    steps:
      - name: 'ğŸ–¥ï¸ Check out repository code'
        uses: actions/checkout@v2
      - name: 'ğŸš§ Install modules'
        run: yarn
      - name: 'ğŸ Run ESLint'
        run: node_modules/.bin/eslint .
